### ISSUE TITLE
Doesnt run in stock JDK 8 when packaged as an executable JAR (e.g. spring boot)

### ISSUE THREAD

**Issue by cameronbraid** [graalvm/graal-js-jdk11-maven-demo#30]
```
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at com.oracle.truffle.polyglot.LanguageCache.collectLanguages(LanguageCache.java:355)
	at com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:247)
	at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:237)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.languages(PolyglotEngineImpl.java:578)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:526)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:198)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:180)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:180)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1406)
	at org.graalvm.polyglot.Context.create(Context.java:700)
	at com.mycompany.app.App.benchGraalPolyglotContext(App.java:123)
	at com.mycompany.app.App.main(App.java:115)
```

demo
git clone https://github.com/cameronbraid/graal-js-jdk11-maven-demo
mvn package exec:exec

**Comment by cameronbraid** [comment]
duplicate of https://github.com/oracle/graal/issues/1348
fixed by https://github.com/oracle/graal/commit/42180c5d084e5c8f413e90c98280c7f83e1163a8
